--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TATCHAN0825/theWarp
build-by-default: true
branches:
  - master
projects:
  theWarp:
    libs:
      - src: CortexPE/Commando/Commando
        version: 3.0.0
        branch: PM4
      - src: Muqsit/SimplePacketHandler/SimplePacketHandler
        version: ^0.0.1
      - src: pjz9n-pm-pl/libi18n/libi18n
        version: 1.0.3
